#!/bin/bash

if echo "${_flag_tty}" | grep -q 'sshd'; then
	LC_COLLATE="C"
	LC_ALL="en_US.UTF-8"
	LC_CTYPE="en_US.UTF-8"
fi

# OPTIONS MENU
_copt() {
	echo -e "##################  \e[94m~~Snapshot~~\e[39m   #################"
	echo "##						 	  ##"
	echo -e "## [ \e[32mI\e[39m  ]	Fetch new	                  ##"
	echo -e "## [ \e[32mII\e[39m ]	Let me show you 		  ##"
	echo -e "## [ \e[32mIII\e[39m]	Try and find it please		  ##"
	echo -e "## [ \e[32mIV\e[39m ]	Where is my shell?		  ##"
	echo -e "## [ \e[32mV\e[39m  ]	Built new from portdir 		  ##"
	echo "##						 	  ##"
	echo "####################################################"
}

# EXPORT CATALYST DIRECTORIES
_export_catalyst_workdirs() {
	# STOREDIR
	export CATDIR=$(grep storedir "${CCONFDIR}/system/catalyst/catalyst.conf" \
	| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

	# PORTDIR
	export CATPORTDIR=$(grep portdir "${CCONFDIR}/system/catalyst/catalyst.conf" \
	| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

	# SNAPSHOT_CACHE
	export CATPORTCACHEDIR=$(grep "snapshot_cache" "${CCONFDIR}/system/catalyst/catalyst.conf" \
	| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

	# PORT_LOGDIR
	export CATLOGDIR=$(grep "port_logdir" "${CCONFDIR}/system/catalyst/catalyst.conf" \
	| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

	# DISTDIR
	export CATDISTDIR=$(grep "distdir" "${CCONFDIR}/system/catalyst/catalyst.conf" \
	| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")
}

# CREATE CATALYST DIRECTORIES
_create_catalyst_workdirs() {
	mkdir -p "${CATDIR}"
	mkdir -p "${CATPORTDIR}"
	mkdir -p "${CATPORTCACHEDIR}"
	mkdir -p "${CATLOGDIR}"
	mkdir -p "${CATDISTDIR}"
	mkdir -p "${CATDIR}/builds/default"
	mkdir -p "${CATDIR}/snapshots"
}

# CALL CATALYST TO CREATE THE SNAPSHOT
_catalyst_snapshot() {
	echo -e "\e[34mCreating snapshot...\e[0m"
	catalyst -s "${SNAPSHOTNAME}" && { BRKVAR=0 && return 0; }|| { BRKVAR=1 && return 1; }
}

# BUILD PORTAGE
_snapshot_builder() {
	echo -e "\e[35mIt is strongly recommended to update your portdir first\e[0m"
	while true; do
		echo "Do you wish to update? Y/N "
		read -rp "Input :: <= " YN
		case "${YN:-n}" in
			[yY][eE][sS]|[yY])
				echo -e "\e[32mUpdating...\e[0m"
				{
				{ eix-sync >/dev/null 2>&1 \
				&& echo -e "\e[32mDone\e[0m" && _catalyst_snapshot; } \
				|| { emerge --sync >/dev/null 2>&1 \
				&& echo -e "\e[32mDone\e[0m" && _catalyst_snapshot; } \
				|| { emerge-webrsync >/dev/null 2>&1 \
				&& echo -e "\e[32mDone\e[0m" && _catalyst_snapshot; }
				} \
				|| { echo -e "\e[31mUpdate failed, build without update?\e[0m"
				while true; do
					echo "Answer: YN "
					read -rp "Input :: <= " ANS
					case "${ANS:-n}" in
						[yY])
							echo -e "\e[34mProceeding\e[0m"
							_catalyst_snapshot
							break;;
						[nN])
							echo -e "\e[34mAborting...\e[0m"
							sleep 1
							BRKVAR=1
							return 0;;
					esac
				done; }
				break;;
			[nN][oO]|[nN])
				echo -e "\e[34mProceeding\e[0m"
				_catalyst_snapshot
				break;;
		esac
	done
}

# SUBTERMINAL
_csubshell() {
	echo -e "\e[33mCalling bash subshell\e[0m"
	sleep 2
	echo 'echo -e "\e[33mInside Subshell\e[0m"' >> /root/.bashrc
	echo "echo -e "Please copy your snapshot to ${CATDIR}/snapshots with name: portage-${SNAPSHOTNAME}.tar.bz2""
	echo 'echo -e "\e[33mExit to return back to parent\e[0m"' >> /root/.bashrc
	(clear; exec /bin/bash;)
	sed -i "/Inside Subshell/d" "/root/.bashrc"
	sed -i "/Exit to return back to parent/d" "/root/.bashrc"
	echo -e "\e[33mYou are back to parent\e[0m"
}

# EXPORT SPEC ENTRIES
_target_paths() {
	TARGETPATH="$(grep 'source_subpath' "${CCONFDIR}/system/catalyst/stage$1.spec" \
	| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $1 }')"

	TARGETNAME="$(grep 'source_subpath' "${CCONFDIR}/system/catalyst/stage$1.spec" \
	| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $2 }')"

	TARGETSTAMP="$(grep 'version_stamp' "${CCONFDIR}/system/catalyst/stage$1.spec" \
	| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"

	SNAPSHOTNAME="$(grep 'snapshot:' "${CCONFDIR}/system/catalyst/stage1.spec" \
	| sed '/^#/ d' | sed '/^\s*$/d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"
}


_fetch_portage() {
if [[ -e "${CATDIR}/portage-latest.tar.bz2" ]]; then
	echo -e "[\e[31m*\e[0m] Purging old snapshot" \
	&& rm -f "${CATDIR}/portage-latest.tar.bz2"
else
	echo -e "[\e[31m*\e[0m] Local backup snapshot was not found!"
fi
	# FETCHING PORTAGE SNAPSHOT
	echo -e "[\e[32m*\e[0m] \e[34mFetchinglatest portage snapshot\e[0m" \
	&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 >/dev/null 2>&1 \
	&& pass && return 0 || die "Failed" 
}

_verify_portage() {
	[[ $(grep portage  "${CATDIR}/portage-latest.tar.bz2.md5sum" | awk -F ' ' '{print $1}') \
	== $(md5sum "${CATDIR}/portage-latest.tar.bz2" |  awk -F ' ' '{ print $1 }') ]] \
	&& echo -e "[\e[32m*\e[0m] Verifying \e[35mmd5sums\e[0m" && return 0 \
	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Verifying \e[31mmd5sums\e[0m"; return 1; }
}

_portage_md5sum() {
	wget -O "${CATDIR}/portage-latest.tar.bz2.md5sum" \
	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2.md5sum >/dev/null 2>&1 \
	&& echo -e "[\e[32m*\e[0m] \e[34mFetching md5sum\e[0m" \
	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: \e[34mFetching md5sum\e[0m" \
	&& return 1; }
}

_simple_fetch() {
	echo -e "[\e[32m*\e[0m] \e[34mFetching latest portage snapshot\e[0m" \
	&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 >/dev/null 2>&1 \
	&& pass && return 0 || die "Failed"
}

_get_latest_snapshot() {
	if [[ -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gsnap'; then
		inspector "$@"
		echo -e "\e[33mForce is active!\e[0m"
		_export_catalyst_workdirs
		rm -f "${CATDIR}/portage-latest.tar.bz2"
		rm -f "${CATDIR}/portage-latest.tar.bz2.md5sum"
		_portage_md5sum
		_simple_fetch
	else
		if [[ -n "${_flag_fetch}" ]]; then
			inspector "$@"
			_export_catalyst_workdirs
			rm -f "${CATDIR}/portage-latest.tar.bz2"
			rm -f "${CATDIR}/portage-latest.tar.bz2.md5sum"
			echo -e "\e[33mSearching for portage snapshot...\e[0m"
			# PORTAGE MD5SUM
			_portage_md5sum
			_simple_fetch
			_verify_portage
		else
			# PORTAGE MD5SUM
			if _portage_md5sum; then
				if _verify_portage; then
					echo "Copying to ${CATDIR}/snapshots" \
					&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
					&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
					&& pass && return 0 || die "Failed"
				else
					echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Snapshot \e[31mverified\e[0m"
					_fetch_portage \
					&& _verify_portage \
					&& echo "Copying to ${CATDIR}/snapshots" \
					&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
					&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
					&& pass && return 0 || die "Failed"
				fi
			else
				die "Failed"
			fi
		fi
	fi
}

# CHECK SNAPSHOT
_snapshot_checkup() {
inspector "$@"
[[ $(du -sh "$1" | awk -F ' ' '{print $1}' | sed 's/[^0-9]*//g') -le 220 ]] \
&& [[ $(du -sh "$1" | awk -F ' ' '{print $1}' | sed 's/[^0-9]*//g') -ge 50 ]] \
|| return 1
}

# SEARCH FOR SNAPSHOTS
_search_snapshot() {
mapfile -t ARRAYSNAP < <(find / -name "*portage*.tar.bz2")


for i in "${ARRAYSNAP[@]}"; do
	if [[ $(du -sh "$i" | awk -F ' ' '{print $1}' | sed 's/[^M]*//g') == M && -n $(echo "$i" | grep portage) ]]; then
		if _snapshot_checkup "$i"; then
			while true; do
				echo "$i"
				echo "Is this the snapshot? Y/N "
				read -rp "Input :: <= " YN
				case "${YN:-5}" in
					[yY][eE][sS]|[yY])
						echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m"
						cp "$i" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"
						return 0
						ESCINNER=0
						break
						;;
					[nN][oO]|[nN])
						ESCINNER=1
						break;;
				esac
			done
			[[ "$ESCINNER" == 0 ]] && unset ESCINNER && break
		fi
	fi
done
return 1
unset YN
unset ESCINNER
unset ARRAYSNAP
}

_stagex() {
	inspector "$@"
	if [[ -e "$1" ]]; then
		# STAGE 2
		echo -e "\e[35mBuilding stage$2\e[0m"

		cat "${CCONFDIR}/system/catalyst/stage$2.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
		> "${CATDIR}/.stage$2.spec"

		#catalyst -c "${CCONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage$2.spec" \
		#&& pass || die "Failed"
	else
		die "Could not locate stage$2-${ARCH}-${TARGETSTAMP}.tar.bz2"
	fi
}

_call_stagex() {
	inspector "$@"
	if [[ -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gcat'; then
		echo -e "\e[31mForce is active!\e[0m"
		_stagex "$1" "$2"
	else
		if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage$2-${ARCH}-${TARGETSTAMP}.tar.bz2" ]]; then

			echo -e "\e[32mStage$2 located\e[0m"
			while read -p "Do you wish to build new? Y/N :: <= " ANS; do
				case $ANS in
					[yY])
						_stagex "$1" "$2"
						break;;
					[nN])
						break;;
				esac
			done
		else
			_stagex "$1" "$2"
		fi
	fi
}
