#!/bin/bash

LC_COLLATE=C

# GET LATEST PORTAGE SNAPSHOT, CREATE GSE PROFILE AND LAST INITIATE THE STAGE 1,2,3 BUILD SEQUENCE

# storedir
CATDIR=$(grep storedir "${CONFDIR}/system/catalyst/catalyst.conf" \
| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

# portdir
CATPORTDIR=$(grep portdir "${CONFDIR}/system/catalyst/catalyst.conf" \
| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

# snapshot_cache
CATPORTCACHEDIR=$(grep "snapshot_cache" "${CONFDIR}/system/catalyst/catalyst.conf" \
| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

# port_logdir
CATLOGDIR=$(grep "port_logdir" "${CONFDIR}/system/catalyst/catalyst.conf" \
| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")
# distdir
CATDISTDIR=$(grep "distdir" "${CONFDIR}/system/catalyst/catalyst.conf" \
| sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")

# CREATE DIRECTORIES FOR CATALYST
mkdir -p "${CATDIR}"
mkdir -p "${CATPORTDIR}"
mkdir -p "${CATPORTCACHEDIR}"
mkdir -p "${CATLOGDIR}"
mkdir -p "${CATDISTDIR}"
mkdir -p "${CATDIR}/builds/default"
mkdir -p "${CATDIR}/snapshots"

# CREATE
TARGETPATH="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage1.spec" \
| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $1 }')"

TARGETNAME="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage1.spec" \
| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $2 }')"

if [[ ! -e "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" ]]; then
cp "${DISTDIR}/dists/stage3-amd64-20170525.tar.bz2" "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2"
fi
unset TARGETNAME
unset TARGETPATH

port_prof_f() {
# GSE PROFILE DIRECTORIES AND FILES
mkdir -p "$1/portage/profiles/gse"
mkdir -p "$1/portage/profiles/defaults/linux/${ARCH}/13.0/gse"

cp "${CONFDIR}/system/portage/profiles/parent-gse/eapi" \
"$1/portage/profiles/gse/eapi" \
&& cp "${CONFDIR}/system/portage/profiles/parent-gse/make.defaults" \
"$1/portage/profiles/gse/make.defaults" \
&& cp "${CONFDIR}/system/portage/profiles/parent-gse/package.use" \
"$1/portage/profiles/gse/package.use" \
&& cp "${CONFDIR}/system/portage/profiles/parent-gse/package.use.force" \
"$1/portage/profiles/gse/package.use.force" \
&& cp "${CONFDIR}/system/portage/profiles/child-gse/eapi" \
"$1/portage/profiles/defaults/linux/${ARCH}/13.0/gse/eapi" \
&& cp "${CONFDIR}/system/portage/profiles/child-gse/parent" \
"$1/portage/profiles/defaults/linux/${ARCH}/13.0/gse/parent" \
&& echo -e "[\e[32m*\e[0m] Creating profile" \
|| { echo -e "[\e[31m*\e[0m] Creating profile"; return 1; }
# END OF GSE PROFILE
}

get_latest_portage_f() {
# PORTAGE MD5SUM
wget -O "${CATDIR}/portage-latest.tar.bz2.md5sum" >/dev/null 2>&1 \
http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2.md5sum \
&& echo -e "[\e[32m*\e[0m] \e[34mGetting md5sum\e[0m" \
|| echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: \e[34mGetting md5sum\e[0m"

# VERIFYING LOCAL SNAPSHOT && FETCH NEW IF VERIFICATION FAILS
BTWRK="${PWD}" && cd "${CATDIR}" >/dev/null 2>&1
if [[ $(md5sum -c "portage-latest.tar.bz2.md5sum") ]]; then
cd "${BTWRK}" >/dev/null 2>&1 \
&& echo -e "[\e[32m*\e[0m] Snapshot \e[32mverified\e[0m" && unset BTWRK
else
cd "${BTWRK}" >/dev/null 2>&1 \
&& echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Snapshot \e[31mverified\e[0m" \
&& echo -e "[\e[31m*\e[0m] Purging old snapshot" \
&& rm -f "${CATDIR}/portage-latest.tar.bz2"
# GETTING PORTAGE SNAPSHOT
echo -e "[\e[32m*\e[0m] \e[34mGetting latest portage snapshot\e[0m" \
&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 \
&& print_inf 1 || { print_inf 2; return 1; } \
&& unset BTWRK

# VERIFYING NEW SNAPSHOT
( BTWRK="${PWD}" && cd "$${CATDIR}/snapshots" >/dev/null 2>&1
[[ $(md5sum -c "portage-latest.tar.bz2.md5sum") ]] \
&&  cd "${BTWRK}" >/dev/null 2>&1 \
&& echo -e "[\e[32m*\e[0m] Snapshot \e[32mverified\e[0m" && unset BTWRK \
|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Snapshot \e[31mverified\e[0m" \
&& unset BTWRK && return 1; }; )

fi

# EXPORT PORTAGE'S NAME
TARGETNAME="$(grep 'snapshot:' "${CONFDIR}/system/catalyst/stage1.spec" \
| sed '/^#/ d' | sed '/^\s*$/d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"

# EXTRACT & CREATE PORTAGE PROFILE
echo -e "\e[34mExtracting snapshot\e[0m"
mkdir -p "${CATDIR}/portage.tmp"

if tar xvjpf "${CATDIR}/portage-latest.tar.bz2" -C "${CATDIR}/portage.tmp" >/dev/null 2>&1; then
echo -e "[\e[32m*\e[0m] Extracted"

port_prof_f "${CATDIR}/portage.tmp" && echo -e "[\e[32m*\e[0m] Portage profile created" \
|| { echo -e "[\e[31m*\e[0m] Profile creation failed"; return 1; }

echo "Building new snapshot"
catalyst -s "${TARGETNAME}" && echo -e "[\e[32m*\e[0m] Done" \
&& if [[ -n "${CATDIR}" ]]; then
	rm -rf "${CATDIR}/portage.tmp" && echo -e "[\e[32m*\e[0m] Purging ${CATDIR}/portage.temp"
	return 0
else
	echo -e "[\e[31m*\e[0m] Could not purge ${CATDIR}/portage.temp"
	return 0
fi \
|| { echo -e "[\e[31m*\e[0m] Failed" && return 1; } 
else
	 echo -e "[\e[31m*\e[0m] Failed" && return 1
fi
unset TARGETNAME
}

tar_path_name_f() {
TARGETPATH="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage$1.spec" \
| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $1 }')"


TARGETNAME="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage$1.spec" \
| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $2 }')"

TARGETSTAMP="$(grep 'version_stamp' "${CONFDIR}/system/catalyst/stage$1.spec" \
| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"
}

opt_f() {
	echo -e "##################  \e[94m~~Snapshot~~\e[39m   #################"
	echo "##						  ##"
	echo -e "## [ \e[32mI\e[39m  ]	Fetch new	                  ##"
	echo -e "## [ \e[32mII\e[39m ]	Let me show you 		  ##"
	echo -e "## [ \e[32mIII\e[39m]	Try and find it please		  ##"
	echo -e "## [ \e[32mIV\e[39m ]	Where is my shell?		  ##"
	echo -e "## [ \e[32mII\e[39m ]	Built new from portdir 		  ##"
	echo "##						  ##"
	echo "####################################################"
}

chk_snap_f() {
[[ $(du -sh "$1" | awk -F ' ' '{print $1}' | sed 's/[^0-9]*//g') -ge 50 \
&& $(du -sh "$1" | awk -F ' ' '{print $1}' | sed 's/[^0-9]*//g') -le 220 ]] \
&& return 0 || return 1
}

search_snap_f() {
mapfile -t ARRAYSNAP < <(find / -name "*.tar.bz2")


for i in "${ARRAYSNAP[@]}"; do
	if [[ $(du -sh "$i" | awk -F ' ' '{print $1}' | sed 's/[^M]*//g') == M && -n $(echo "$i" | grep portage) && -z $(echo "$i" | grep "gcc") ]]; then
		if chk_snap_f "$i"; then
			while true; do
				echo "$i"
				read -rp "Is this the snapshot? Y/N " YN
				case "$YN" in
					[yY][eE][sS]|[yY])
						echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m"
						cp "$i" "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2"
						return 0
						ESCINNER=0
						break
						;;
					[nN][oO]|[nN])
						ESCINNER=1
						break;;
				esac
			done
			[[ "$ESCINNER" == 0 ]] && unset ESCINNER && break
		fi
	fi
done
return 1
unset YN
unset ARRAYSNAP
}

build_port() {
	echo -e "\e[35mIt is strongly recommended to update your portdir first\e[0m"
	while true; do
		read -rp "Do you wish to update? Y/N "
		case "$YN" in
			[yY][eE][sS]|[yY])
				if emerge --sync; then
					catalyst -s "${TARGETNAME}" && { BRKVAR=0 && return 0; }|| { BRKVAR=1 && return 1; }
				elif eix-sync; then
					catalyst -s "${TARGETNAME}" && { BRKVAR=0 && return 0; }|| { BRKVAR=1 && return 1; }
				elif emerge-webrsync; then
					catalyst -s "${TARGETNAME}" && { BRKVAR=0 && return 0; }|| { BRKVAR=1 && return 1; }
				else
					catalyst -s "${TARGETNAME}" && { BRKVAR=0 && return 0; }|| { BRKVAR=1 && return 1; }
				fi
				break;;
			[nN][oO]|[nN])
				catalyst -s "${TARGETNAME}" && { BRKVAR=0 && return 0; }|| { BRKVAR=1 && return 1; }
				break;;
		esac
	done
}

TARGETNAME="$(grep 'snapshot:' "${CONFDIR}/system/catalyst/stage1.spec" \
| sed '/^#/ d' | sed '/^\s*$/d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"

if [[ ! -e "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2" ]]; then
while true; do
	opt_f
	echo -e "[\e[31m*\e[0m] Could not locate snapshots/portage-${TARGETNAME}.tar.bz2 @ ${CATDIR}/snapshots"
	echo "Please select an option"
	read -rp "Option: " ANS
	case "$ANS" in
		I|i|1)
			get_latest_portage_f && BRKVAR=0 || BRKVAR=1
			;;
		II|ii|2)
			read -rp "Please enter the absolute path with the snapshot included: " PATHTOSNAP
			if [[ -n $(chk_snap_f "${PATHTOSNAP}") ]]; then
				cp "${PATHTOSNAP}" "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2" \
				&& echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m" && BRKVAR=0 || BTWRK=1				
			else
				echo -e "\e[31mThe file you entered is either a heavily modified snapshot or not a snapshot"
				while true; do
					read -rp "Do you wish to proceed? Y/N" YN
					case "$YN" in
						[yY][eE][sS]|[yY])
							echo -e "\e[34mCopying file to ${CATDIR}/snapshots\e[0m"
							cp "${PATHTOSNAP}" "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2\e[0m"
							BRKVAR=0
							break;;
						[nN][oO]|[nN])
							BRKVAR=1
							break;;
					esac
				done
			fi
			unset PATHTOSNAP
			unset YN
			break;;
		III|iii|3)
			echo -e "\e[32mSearching\e[0m..."
			search_snap_f && echo -e "\e[32mChecking\e[0m..." || { echo -e "\e[31mCould not locate the snapshot\e[0m"; BRKVAR=1; }
			echo -e "[\e[32m*\e[0m]  Located the snapshot"
			if chk_snap_f "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2"; then
				echo -e "[\e[32m*\e[0m]  Snapshot seems normal"
				BRKVAR=0
			else
				echo -e "[\e[31m*\e[0m] Snapshot located but it's size is out of normal boundaries"
				while true; do
					read -rp "Do you wish to continue? Y/N "
					case "$YN" in
						[yY][eE][sS]|[yY])
							echo -e "[\e[32m*\e[0m] Proceeding"
							BRKVAR=0
							break;;
						[nN][oO]|[nN])
							echo -e "[\e[31m*\e[0m] Returning options"
							BRKVAR=1
							break;;
					esac
				done
			fi
			;;
		IV|iv|4)
			echo "\e[35mOpening new shell, please copy your snapshot to ${CATDIR}/snapshots with name: portage-${TARGETNAME}.tar.bz2\e[0m"
			sleep 5
			exec /bin/bash
			if [[ -e "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2" ]]; then
				echo -e "\e[32mChecking\e[0m..."
				if chk_snap_f "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2"; then
					echo -e "[\e[32m*\e[0m]  Snapshot seems normal"
					BRKVAR=0
				else
					echo -e "[\e[31m*\e[0m] Snapshot located but it's size is out of normal boundaries"
					while true; do
						read -rp "Do you wish to continue? Y/N "
						case "$YN" in
							[yY][eE][sS]|[yY])
								echo -e "[\e[32m*\e[0m] Proceeding"
								BRKVAR=0
								break;;
							[nN][oO]|[nN])
								echo -e "[\e[31m*\e[0m] Returning options"
								BRKVAR=1
								break;;
						esac
					done
				fi
			else
				echo -e "[\e[31m*\e[0m] Could not locate the snapshot"
				echo -e "[\e[31m*\e[0m] Returning options"
				BRKVAR=1
			fi
			;;
		V|v|5)
			if [[ (($(ls -A "${CATPORTDIR}" | grep 'app-portage') != 'app-portage')) ]]; then
				echo -e "[\e[32m*\e[0m] ${CATPORTDIR} does not look like a normal portage location"
				while true; do
					read -rp "Do you wish to continue? Y/N "
					case "$YN" in
						[yY][eE][sS]|[yY])
							port_prof_f "${CATPORTDIR}" \
							&& build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
							;;
						[nN][oO]|[nN])
							while true; do
								read -rp "Do you wish to give a new portdir location? Y/N "
								case $YN in
									[yY][eE][sS]|[yY])
										read -rp "Portdir's absolute path: " CATPORTDIR
										if [[ (($(ls -A "${CATPORTDIR}" | grep 'app-portage') != 'app-portage')) ]]; then
											echo "Neither this location looks to contain a normal portage directory"
											while true; do
												read -rp "Do you wish to proceed? Y/N "
												case $YN in
													[yY][eE][sS]|[yY])
														export CATPORTDIR
														port_prof_f "${CATPORTDIR}" \
														&& build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
														;;
													[nN][oO]|[nN])
														echo -e "[\e[31m*\e[0m] Returning back to options"
														BRKVAR=1
														break;;
												esac
											done
										else
											port_prof_f "${CATPORTDIR}" \
											&& build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
										fi
										break;;
									[nN][oO]|[nN])
										echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
										BRKVAR=1
										break;;
								esac
							done
							;;
					esac
				done
			else
				port_prof_f "${CATPORTDIR}" \
				&& build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
			fi
			;;
	esac
	[[ "${BRKVAR}" == 0 ]] && break
done
else
	echo -e "\e[32mPrtage snapshot found @ ${CATDIR}/snapshots\e[0m"

fi
unset BRKVAR
unset TARGETNAME

tar_path_name_f 1
unset TARGETPATH

TARGETPATH="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage1.spec" \
| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $1}')"

stage1_f() {
if [[ -e "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" ]]; then
# STAGE 1

echo -e "\e[35mBuilding stage1\e[0m"

cat "${CONFDIR}/system/catalyst/stage1.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
> "${CATDIR}/.stage1.spec"

catalyst -c "${CONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage1.spec" \
&& print_inf 1 || { print_inf 2 && exit 1; }
else
 echo -e "\e[31mCould not locate ${TARGETNAME}.tar.bz2\e[0m"
fi
}

if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage1-amd64-${TARGETSTAMP}.tar.bz2" && "$3" == "s1" ]]; then

echo -e "\e[32mStage1 located\e[0m"

while read -p "Do you wish to build new? Y/N " ANS; do
	case $ANS in
		[yY])
			stage1_f
			break;;
		[nN])
			break;;
	esac
done
else
stage1_f
fi

unset TARGETNAME
unset TARGETPATH
unset TARGETSTAMP
tar_path_name_f 2

stage2_f() {
if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage1-amd64-${TARGETSTAMP}.tar.bz2" ]]; then
# STAGE 2
echo -e "\e[35mBuilding stage2\e[0m"

cat "${CONFDIR}/system/catalyst/stage2.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
> "${CATDIR}/.stage2.spec"

catalyst -c "${CONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage2.spec" \
&& print_inf 1 || { print_inf 2 && exit 1; }
else
 echo -e "\e[31mCould not locate stage1-amd64-${TARGETSTAMP}.tar.bz2\e[0m"
fi
}

if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage2-amd64-${TARGETSTAMP}.tar.bz2" && "$4" == "s2" ]]; then

echo -e "\e[32mStage2 located\e[0m"

while read -p "Do you wish to build new? Y/N " ANS; do
	case $ANS in
		[yY])
			stage2_f
			break;;
		[nN])
			break;;
	esac
done
else
stage2_f
fi

unset TARGETNAME
unset TARGETPATH
unset TARGETSTAMP
tar_path_name_f 3

stage3_f() {
if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage2-amd-64-${TARGETSTAMP}.tar.bz2" ]]; then
# STAGE 3

echo -e "\e[35mBuilding stage3\e[0m"

cat "${CONFDIR}/system/catalyst/stage3.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
> "${CATDIR}/.stage3.spec"

catalyst -c "${CONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage3.spec" \
&& print_inf 1 || { print_inf 2 && exit 1; }
else
 echo -e "\e[31mstage2-amd-64-${TARGETSTAMP}.tar.bz2\e[0m"
fi
}

if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage3-amd64-${TARGETSTAMP}.tar.bz2" && "$5" == "s3" ]]; then

echo -e "\e[32mStage3 located\e[0m"

while read -p "Do you wish to build new? Y/N " ANS; do
	case $ANS in
		[yY])
			stage3_f
			break;;
		[nN])
			break;;
	esac
done
else
stage3_f
fi

unset ANS
unset TARGETNAME
unset TARGETPATH
unset TARGETSTAMP
unset CATDIR
unset CATPORTDIR
unset CATPORTCACHEDIR
unset CATLOGDIR
unset CATDISTDIR