#!/bin/bash

# THIS SCRIPT IS SOURCED AT THE BEGINING FOR CHECKING THE BUILDER'S RUNTIME DEPENDENCIES

amiroot() {
	if [[ "$1" == "0" ]]
	then
		return 0
	else
		return 1
	fi
}

[[ -n $(whereis eix | awk -F ':' '{ print $2 }' | sed '/^\s*$/d') ]] \
|| { echo -e "[\e[33m*\e[0m] \e[35mPlease install eix to proceed!\e[0m" \
&& { amiroot $UID && echo -e "[\e[32m*\e[0m] Root privileges found" \
&& emerge -aq eix && echo -e "[\e[33m*\e[0m] \e[35mUpdating database\e[0m" \
&& eix-sync -a >/dev/null 2>&1; } \
|| { echo -e "[\e[31m*\e[0m] Could not get root privileges" \
&& echo "Please resolve this issue and start again" && exit 1; }; }

mapfile -t lreq < <(cat "${LOCALLG}/loc_req" | sed '/^#/ d' | sed '/^\s*$/d')

for i in "${lreq[@]}"; do
sleep 0.1
if eix --installed $i >/dev/null 2>&1; then
echo -e "[\e[32m*\e[0m] Searching for \e[32m$i\e[0m"
else
echo -e "[\e[31m*\e[0m] Searching for $i"
echo -e "[\e[33m*\e[0m] Attempting to resolve the missing dependency"
amiroot $UID && echo -e "[\e[32m*\e[0m] Root privileges found" \
&& emerge -aq "$i" \
|| { echo -e "[\e[31m*\e[0m] Could not get root privileges" \
&& echo "Please resolve this issue and start again" && exit 1; }
fi
done