#!/bin/bash

# THIS SCRIPT IS SOURCED AT THE BEGINING FOR CHECKING THE BUILDER'S RUNTIME DEPENDENCIES
CRDPENDS=''
amiroot() {
	if [[ "$1" == "0" ]]
	then
		return 0
	else
		return 1
	fi
}
case "$1" in
1)
[[ -n $(command -v eix | awk -F ':' '{ print $2 }' | sed '/^\s*$/d') ]] \
|| { echo -e "[\e[33m*\e[0m] \e[35mPlease install eix to proceed!\e[0m" \
&& { amiroot $UID && echo -e "[\e[32m*\e[0m] Root privileges found" \
&& emerge -aq eix && echo -e "[\e[33m*\e[0m] \e[35mUpdating database\e[0m" \
&& eix-sync -a >/dev/null 2>&1; } \
|| { echo -e "[\e[31m*\e[0m] Could not get root privileges" \
&& echo "Please resolve this issue and start again" && exit 1; }; }

mapfile -t lreq < <(cat "${CLOCALLG}/loc_req" | sed '/^#/ d' | sed '/^\s*$/d')

for i in "${lreq[@]}"; do
sleep 0.1
if eix --installed "$i" >/dev/null 2>&1; then
echo -e "[\e[32m*\e[0m] Searching for \e[32m$i\e[0m"
else
echo -e "[\e[31m*\e[0m] Searching for $i"
echo -e "[\e[33m*\e[0m] Attempting to resolve the missing dependency"
amiroot $UID && echo -e "[\e[32m*\e[0m] Root privileges found" \
&& emerge -aq "$i" \
|| { echo -e "[\e[31m*\e[0m] Could not get root privileges" \
&& echo "Please resolve this issue and start again" && exit 1; }
fi
done;;
2)
mapfile -t lreq < <(cat "${CLOCALLG}/nogloc_req" | sed '/^#/ d' | sed '/^\s*$/d')

for i in "${lreq[@]}"; do
sleep 0.1
if command -v "$i" >/dev/null 2>&1; then
echo -e "[\e[32m*\e[0m] Searching for \e[32m$i\e[0m"
else
echo -e "[\e[31m*\e[0m] Searching for $i"
CRDPENDS=1
fi
done
[[ "${CRDPENDS}" == 1 ]] && while true; do
	echo -e "\e[33mIf you think some of those dependencies are name missmatch or not important\e[0m"
	echo -e "\e[33mYou can choose to continue at your own ristk\e[0m"
	read -rp "Continue? Y/N: " ANS
	case "${ANS}" in
		[yY])
			break;;
		[nN])
			echo "Exiting..." && sleep 1 && exit 1;;
	esac
done
esac