#!/bin/bash

# MAIN MENU OF /bin/gse
	case $1 in
		1 )
			echo -e "######################  \e[94m~~Main Menu~~\e[39m   #####################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	     \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				  \e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##							   ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mSystem menu\e[0m		   	           ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mBuild the controller image\e[0m		   ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mGSE Tools\e[0m				   ##"
			echo -e "## [ \e[32mIV\e[39m ]	\e[33mDocumentations\e[0m				   ##"
			echo -e "## [ \e[32mV\e[39m  ]	\e[33mAbout the project\e[0m			   ##"
			echo -e "## [ \e[32mVI\e[39m ]	\e[33mI shouldn't be here, please let me leave!\e[0m  ##"
			echo "##							   ##"
			echo -e "## [ \e[32mT\e[39m  ]				  \e[32mTerminal\e[0m	   ##"
			echo "##							   ##"
			echo "#############################################################"
			;;
		2 )
			echo -e "###################  \e[94m~~Documentations~~\e[39m   ####################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	      \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				   \e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##							    ##"
			echo -e "## [ \e[32mI\e[39m   ]	\e[33mIntroduction to GSE Directory\e[0m		    ##"
			echo -e "## [ \e[32mII\e[39m  ]	\e[33mThe Controller\e[0m 				    ##"
			echo -e "## [ \e[32mIII\e[39m ]	\e[33mThe Config.d Directory\e[0m		 	    ##"
			echo -e "## [ \e[32mIV\e[39m  ]	\e[33mThe dist.d Directory\e[0m			    ##"
			echo -e "## [ \e[32mV\e[39m   ]	\e[33mMain Menu\e[0m 				    ##"
			echo "##							    ##"
			echo "##############################################################"
			;;
		3 )
			echo -e "#######################  \e[94m~~About~~\e[39m   ########################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	     \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				  \e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##							   ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mAbout the project\e[0m			   ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mLinux, Gentoo and the birth of an Idea\e[0m	   ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mOpen Source To The End and Beyond\e[0m	   ##"
			echo -e "## [ \e[32mIV\e[39m ]	\e[33mMain Menu\e[0m 				   ##"
			echo "##							   ##"
			echo "#############################################################"
			;;
		5)
			echo -e "######################  \e[94m~~Builder~~\e[39m   #####################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	   \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				\e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						         ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mBuilt a System\e[0m 		                 ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mConfigure built variables\e[0m		 ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mSelect default system for distribution\e[0m	 ##"
			echo -e "## [ \e[32mIV\e[39m ]	\e[33mCreate a stage4 tarball\e[0m			 ##"
			echo -e "## [ \e[32mV\e[39m  ]	\e[33mReturn back\e[0m  				 ##"
			echo "##							 ##"
			echo -e "## [ \e[32mT\e[39m  ]				\e[32mTerminal\e[0m	 ##"
			echo "##							 ##"
			echo "###########################################################"
			;;
		6)
			echo -e "#################  \e[94m~~System Menu~~\e[39m   ################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 			  	     \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 			  \e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						   ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mPortage\e[0m		  	           ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mCatalyst\e[0m			   ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mPrecompiled\e[0m		   	   ##"
			echo -e "## [ \e[32mIV\e[39m ]	\e[33mReturn back\e[0m  			   ##"
			echo "##						   ##"
			echo -e "## [ \e[32mT\e[39m  ]		  		\e[32mTerminal\e[0m   ##"
			echo "##						   ##"
			echo "#####################################################"
			;;
		7)
			echo -e "######################  \e[94m~~Portage~~\e[39m   #####################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	   \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				\e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						         ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mGuided/Automatic make.conf\e[0m	 	 ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mManually edit make.conf (Reset)\e[0m  	 ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mFeatures & ccashe\e[0m		  	 ##"
			echo -e "## [ \e[32mIV\e[39m ]	\e[33mEdit distcc\e[0m	                 	 ##"
			echo -e "## [ \e[32mV\e[39m  ]	\e[33mEdit packages.use\e[0m			 ##"
			echo -e "## [ \e[32mVI\e[39m ]	\e[33mReview packages.use\e[0m	 		 ##"
			echo -e "## [ \e[32mVII\e[39m]	\e[33mRestore packages.use\e[0m	 		 ##"
			echo -e "## [\e[32mVIII\e[39m]	\e[33mReturn back\e[0m  				 ##"
			echo "##							 ##"
			echo -e "## [ \e[32mT\e[39m  ]				\e[32mTerminal\e[0m	 ##"
			echo "##							 ##"
			echo "###########################################################"
			;;
		8)
			echo -e "##################  \e[94m~~Configurations~~\e[39m   ##################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	   \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				\e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						         ##"
			echo -e "## [ \e[32mI\e[39m    ]	\e[33mConfigure fstab/drives\e[0m	      	         ##"
			echo -e "## [ \e[32mII\e[39m   ]	\e[33mManually edit fstab\e[0m	 		 ##"
			echo -e "## [ \e[32mIII\e[39m  ]	\e[33mManually edit drive names\e[0m		 ##"
			echo -e "## [ \e[32mIV\e[39m   ]	\e[33mEdit Hostname\e[0m				 ##"
			echo -e "## [ \e[32mV\e[39m    ]	\e[33mEdit /etc/conf.d/net\e[0m			 ##"
			echo -e "## [ \e[32mVI\e[39m   ]	\e[33mEdit Locales\e[0m				 ##"
			echo -e "## [ \e[32mVII\e[39m  ]	\e[33mEdit Consolefont\e[0m			 ##"
			echo -e "## [ \e[32mVIII\e[39m ]	\e[33mEdit sshd\e[0m		 	 	 ##"
			echo -e "## [ \e[32mIX\e[39m   ]	\e[33mEdit sshkey\e[0m		 	 	 ##"
			echo -e "## [ \e[32mX\e[39m    ]	\e[33mSymlink, bind, overlay and tmpfs\e[0m	 ##"
			echo -e "## [ \e[32mXI\e[39m   ]	\e[33mAdd Scripts\e[0m				 ##"
			echo -e "## [ \e[32mXII\e[39m  ]	\e[33mInstall Packages\e[0m			 ##"
			echo -e "## [ \e[32mXIII\e[39m ]	\e[33mEdit Default Grub\e[0m			 ##"
			echo -e "## [ \e[32mXIV\e[39m  ]	\e[33mEdit runlevels***\e[0m			 ##"
			echo -e "## [ \e[32mXV\e[39m   ]	\e[33mInject files\e[0m				 ##"
			echo -e "## [ \e[32mXVI\e[39m  ]	\e[33mReturn back\e[0m  				 ##"
			echo "##							 ##"
			echo -e "## [  \e[32mT\e[39m   ]				\e[32mTerminal\e[0m	 ##"
			echo "##							 ##"
			echo "###########################################################"
			;;
		9)
			echo -e "##################  \e[94m~~Select Default~~\e[39m   ##################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	   \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				\e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						         ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mList systems\e[0m		                 ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mEdit default\e[0m				 ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mReturn back\e[0m				 ##"
			echo "##							 ##"
			echo -e "## [ \e[32mT\e[39m  ]				\e[32mTerminal\e[0m	 ##"
			echo "##							 ##"
			echo "###########################################################"
			;;
		10)
			echo -e "###################  \e[94m~~Catalyst~~\e[39m   #################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 			  \e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						   ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mConfigure catalyst.conf\e[0m	           ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mConfigure catalystrc\e[0m		   ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mConfigure stage1\e[0m  		   ##"
			echo -e "## [ \e[32mIV\e[39m ]	\e[33mConfigure stage2\e[0m  		   ##"
			echo -e "## [ \e[32mV\e[39m  ]	\e[33mConfigure stage3\e[0m  		   ##"
			echo -e "## [ \e[32mVI\e[39m ]	\e[35mInitiate Build\e[0m			   ##"
			echo -e "## [ \e[32mVII\e[39m]	\e[33mReturn\e[0m  			   ##"
			echo "##						   ##"
			echo -e "## [ \e[32mT\e[39m  ]		  		\e[32mTerminal\e[0m   ##"
			echo "##						   ##"
			echo "#####################################################"
			;;
		11)
			echo -e "####################  \e[94m~~GSE Tools~~\e[39m   #####################"
			if [[ "${CREL}" == Gentoo ]]; then
				echo -e "## 				     	   \e[35m${CREL}\e[0m \e[33msystem\e[0m ##"
			else
				echo -e "## 				\e[35mGentoo\e[0m \e[31msystem not found!\e[0m ##"
			fi
			echo "##						         ##"
			echo -e "## [ \e[32mI\e[39m  ]	\e[33mRenew ALL\e[0m		                 ##"
			echo -e "## [ \e[32mII\e[39m ]	\e[33mVersion Check\e[0m				 ##"
			echo -e "## [ \e[32mIII\e[39m]	\e[33mReturn back\e[0m				 ##"
			echo "##							 ##"
			echo -e "## [ \e[32mT\e[39m  ]				\e[32mTerminal\e[0m	 ##"
			echo "##							 ##"
			echo "###########################################################"
			;;
	esac	