#!/bin/bash

_ct_conf() {
	_ct_arg_ar=("include" "cmdline" "hook" "net" "module-probe" \
		"module-insmod" "module-auto" "module-blacklist" "dracut_opt")
	if grep -q "force" "${CTCONFDIR}/confdir/cdevname.info" | sed '/^#/ d' | sed '/^\s*$/d'; then
		_controller_args '--force'
	fi
	
	for i in "${_ct_arg_ar[@]}"; do
		if grep -q "$i" "${CTCONFDIR}/confdir/cdevname.info" | sed '/^#/ d' | sed '/^\s*$/d' | awk -F '=' '{ print $2 }'; then
			_TMPR099="$(grep "$i" "${CTCONFDIR}/confdir/cdevname.info" | sed '/^#/ d' | sed '/^\s*$/d' | awk -F '=' '{ print $2 }')"
			_controller_args "${_TMPR099}"
		fi
	done
}


_make_image() {
	dracut --force --show-modules --printsize --nostrip  --early-microcode \
	--fscks "fsck.btrfs fsck.ext4 fsck.fat fsck.hfs fsck.hfsplus fsck.jfs fsck.minix fsck.reiser4 fsck.reiserfs fsck.vfat fsck.xfs" \
	--filesystems "btrfs ext4 fat hfs hfsplus jfs minix reiser4 reiserfs vfat xfs" \
	"${CDISTDIR}/initramfs-${GSEVER}-4.9.16-gentoo"
}