#!/bin/bash

# FLAGS AND ARGUMENTS
_controller_args() {
	while true; do
		[[ -z "$*" ]] && return 0
		case "$1" in
			--build-controller*|-bc*	)
				if [[ "$1" != *'='* ]]; then
					die "Missing argument for controller's path"
				else
					_flag_controller_path="${1#*=}"
					
					if [[ ${_flag_controller_path:0:1} != "/" ]]; then
						_flag_controller_path="/${_flag_controller_path}"
					fi

					if [[ "${_flag_controller_path}" == '/' ]]; then
						die "Root is not allowed to be set as moddir path. Aborting..."
					else
						if [[ -d "${_flag_controller_path}" ]]; then
							_flag_controller=0
							export _flag_controller
							export _flag_controller_path
							_e_report_back "Controller flag enabled"
						else
							die "Error: moddir's target is not a directory"
						fi
					fi
				fi
			*							)
				die "Unknown $1 operation"
				;;
		esac
		shift
	done
}

_controller_args "$@"

_make_image() {
	dracut --force --show-modules --printsize --nostrip  --early-microcode \
	--fscks "fsck.btrfs fsck.ext4 fsck.fat fsck.hfs fsck.hfsplus fsck.jfs fsck.minix fsck.reiser4 fsck.reiserfs fsck.vfat fsck.xfs" \
	--filesystems "btrfs ext4 fat hfs hfsplus jfs minix reiser4 reiserfs vfat xfs" \
	"${CDISTDIR}/initramfs-${GSEVER}-4.9.16-gentoo"
}