#!/bin/bash
# This is an example catalystrc. As such, it doesn't actually *do* anything.

# Uncomment the following to increase the number of threads used to compile.
# export MAKEOPTS="-j16"
#
# The following options simply exports MAKEOPTS="-j{system's cores}"
# Example: For a quadcore system -> export MAKEOPTS="-j5"
MKCORES$(( $(grep -c ^processor /proc/cpuinfo) + 1 ))
export MAKEOPTS="-j${MKCORES}"
